"""create user table

Revision ID: a1ddc9d52404
Revises: 
Create Date: 2026-02-20 22:18:16.794626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ddc9d52404'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('mobile', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('gender', sa.String(length=1), nullable=True, comment='性别（1男、2女、0未知物种'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='全局唯一标识'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_user_create_time'), 'sys_user', ['create_time'], unique=False)
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_mobile'), 'sys_user', ['mobile'], unique=True)
    op.create_index(op.f('ix_sys_user_updated_time'), 'sys_user', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_index(op.f('ix_sys_user_uuid'), 'sys_user', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_uuid'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_updated_time'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_mobile'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_create_time'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
